#!/bin/bash
# Copyright © 2021 Kris Nóva <kris@nivenly.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#  ────────────────────────────────────────────────────────────────────────────
#
#   ████████╗██╗    ██╗██╗███╗   ██╗██╗  ██╗
#   ╚══██╔══╝██║    ██║██║████╗  ██║╚██╗██╔╝
#      ██║   ██║ █╗ ██║██║██╔██╗ ██║ ╚███╔╝
#      ██║   ██║███╗██║██║██║╚██╗██║ ██╔██╗
#      ██║   ╚███╔███╔╝██║██║ ╚████║██╔╝ ██╗
#      ╚═╝    ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
#
#  ────────────────────────────────────────────────────────────────────────────
HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd ${HERE}

VERSION="1.2.2"
rm -rf *${VERSION}*

# nginx main
echo "-----------------------------"
echo "Downloading nginx..."
echo "-----------------------------"
echo ""
wget https://nginx.org/download/nginx-${VERSION}.tar.gz
tar -xzf  nginx-${VERSION}.tar.gz

# nginx RTMP module
echo "-----------------------------"
echo "Download nginx rtmp module..."
echo "-----------------------------"
echo ""
wget https://github.com/arut/nginx-rtmp-module/archive/refs/tags/v${VERSION}.tar.gz
tar -xzf v${VERSION}.tar.gz

# nginx 1.2.2 will sysctl.h>/sysctl.h> which was moved to <linux/sysctl.h> in newer versions of the kernel.

grep -rl "#include <sys/sysctl.h>" ./nginx-rtmp-module-${VERSION} | xargs sed -i 's|#include <sys/sysctl.h>|#include <linux/sysctl.h>|g'

grep -rl "#include <sys/sysctl.h>" ./nginx-${VERSION} | xargs sed -i 's|#include <sys/sysctl.h>|#include <linux/sysctl.h>|g'

cd nginx-${VERSION}
# Configure notes: https://linuxhit.com/nginx-rtmp-statement-may-fall-through/
./configure --add-module=../nginx-rtmp-module-${VERSION} --with-cc-opt="-Wimplicit-fallthrough=0"
make
sudo -E make install
