#!/bin/bash
# Copyright © 2021 Kris Nóva <kris@nivenly.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#  ────────────────────────────────────────────────────────────────────────────
#
#   ████████╗██╗    ██╗██╗███╗   ██╗██╗  ██╗
#   ╚══██╔══╝██║    ██║██║████╗  ██║╚██╗██╔╝
#      ██║   ██║ █╗ ██║██║██╔██╗ ██║ ╚███╔╝
#      ██║   ██║███╗██║██║██║╚██╗██║ ██╔██╗
#      ██║   ╚███╔███╔╝██║██║ ╚████║██╔╝ ██╗
#      ╚═╝    ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
#
#  ────────────────────────────────────────────────────────────────────────────
HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd ${HERE}

echo "Stopping..."
sudo twinx stream stop

echo "Cleaning..."
sudo rm -rf /var/run/twinx.*

echo "Building..."
./make-install

echo "Starting..."
sudo twinx stream start "Title" "Description"

echo "Serving..."
sudo twinx rtmp start

echo "Proxying..."
sudo twinx rtmp proxy rtmp://newyork.restream.io/live/${RESTREAM_KEY}
